#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

if [ $# -eq 0 ]; then
    echo "Usage: $0 <path-to-openapi-spec>"
    exit 1
fi

pnpx @hey-api/openapi-ts \
  -f ./openapi-ts.config.ts \
  -i $1 \
  -o out
