#!/usr/bin/env bash

set -e

cd -- "$(dirname -- "$0")/.."

pnpm start-server-and-test --expect 404 \
  "pnpm prism mock -d --json-schema-faker-fillProperties=false specs/ai-guard.openapi.json" \
  4010 \
  "pnpm test tests/ai-guard.test.ts"
